# Generated by Django 5.0.6 on 2024-06-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_casual_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='CH_leave',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('leave_type', models.CharField(default='CH Leave', max_length=50)),
                ('date_Applied', models.CharField(max_length=50)),
                ('from_Date', models.CharField(max_length=50)),
                ('to_Date', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=50)),
                ('remaining', models.CharField(default='-', max_length=50)),
                ('total_leave', models.FloatField(default=0)),
                ('status', models.CharField(default='Reviewing', max_length=50)),
                ('unique_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(default='-', max_length=200)),
                ('document', models.FileField(upload_to='leave_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='earnLeave',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('leave_type', models.CharField(default='Earn Leave', max_length=50)),
                ('date_Applied', models.CharField(max_length=50)),
                ('from_Date', models.CharField(max_length=50)),
                ('to_Date', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=50)),
                ('remaining', models.CharField(default='-', max_length=50)),
                ('total_leave', models.FloatField(default=0)),
                ('status', models.CharField(default='Reviewing', max_length=50)),
                ('unique_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(default='-', max_length=200)),
                ('document', models.FileField(upload_to='leave_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='LOP_leave',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('leave_type', models.CharField(default='LOP Leave', max_length=50)),
                ('date_Applied', models.CharField(max_length=50)),
                ('from_Date', models.CharField(max_length=50)),
                ('to_Date', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=50)),
                ('remaining', models.CharField(default='-', max_length=50)),
                ('total_leave', models.FloatField(default=0)),
                ('status', models.CharField(default='Reviewing', max_length=50)),
                ('unique_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(default='-', max_length=200)),
                ('document', models.FileField(upload_to='leave_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='medicalLeave',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('leave_type', models.CharField(default='Medical Leave', max_length=50)),
                ('date_Applied', models.CharField(max_length=50)),
                ('from_Date', models.CharField(max_length=50)),
                ('to_Date', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=50)),
                ('remaining', models.CharField(default='-', max_length=50)),
                ('total_leave', models.FloatField(default=0)),
                ('status', models.CharField(default='Reviewing', max_length=50)),
                ('unique_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(default='-', max_length=200)),
                ('document', models.FileField(upload_to='leave_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='onDuty',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('leave_type', models.CharField(default='Onduty', max_length=50)),
                ('date_Applied', models.CharField(max_length=50)),
                ('from_Date', models.CharField(max_length=50)),
                ('to_Date', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=50)),
                ('remaining', models.CharField(default='-', max_length=50)),
                ('total_leave', models.FloatField(default=0)),
                ('status', models.CharField(default='Reviewing', max_length=50)),
                ('unique_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(default='-', max_length=200)),
                ('document', models.FileField(upload_to='leave_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='specialOnduty',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('leave_type', models.CharField(default='Special Onduty', max_length=50)),
                ('date_Applied', models.CharField(max_length=50)),
                ('from_Date', models.CharField(max_length=50)),
                ('to_Date', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=50)),
                ('remaining', models.CharField(default='-', max_length=50)),
                ('total_leave', models.FloatField(default=0)),
                ('status', models.CharField(default='Reviewing', max_length=50)),
                ('unique_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(default='-', max_length=200)),
                ('document', models.FileField(upload_to='leave_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='vaccationLeave',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('leave_type', models.CharField(default='Vaccation Leave', max_length=50)),
                ('date_Applied', models.CharField(max_length=50)),
                ('from_Date', models.CharField(max_length=50)),
                ('to_Date', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=50)),
                ('remaining', models.CharField(default='-', max_length=50)),
                ('total_leave', models.FloatField(default=0)),
                ('status', models.CharField(default='Reviewing', max_length=50)),
                ('unique_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(default='-', max_length=200)),
                ('document', models.FileField(upload_to='leave_documents/')),
            ],
        ),
    ]
