# Generated by Django 5.0.6 on 2024-06-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_ch_leave_earnleave_lop_leave_medicalleave_onduty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casual_leave',
            name='date_Applied',
            field=models.DateField(max_length=50),
        ),
    ]
