# Generated by Django 5.0.6 on 2024-06-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_casual_leave_date_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casual_leave',
            name='date_Applied',
            field=models.DateTimeField(max_length=50),
        ),
    ]
