# Generated by Django 5.0.6 on 2024-06-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_alter_casual_leave_date_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ch_leave',
            name='date_Applied',
            field=models.DateTimeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='earnleave',
            name='date_Applied',
            field=models.DateTimeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lop_leave',
            name='date_Applied',
            field=models.DateTimeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalleave',
            name='date_Applied',
            field=models.DateTimeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='onduty',
            name='date_Applied',
            field=models.DateTimeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='specialonduty',
            name='date_Applied',
            field=models.DateTimeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vaccationleave',
            name='date_Applied',
            field=models.DateTimeField(max_length=50),
        ),
    ]
