# Generated by Django 5.0.6 on 2024-06-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_alter_ch_leave_date_applied_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('Announcement', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
