# Generated by Django 5.0.6 on 2024-06-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_announcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='Announcement',
            new_name='announcement',
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='CH_leave_avail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='LOP_leave_avail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='casual_leave_avail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='earnLeave_avail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='medicalLeave_avail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='onDutye_avail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='specialOnduty_avail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='vaccationLeave_avail',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='timestamp',
            field=models.DateTimeField(max_length=50),
        ),
    ]
