# Generated by Django 5.0.6 on 2024-06-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_alter_staffdetails_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='department',
            field=models.CharField(choices=[('ECE', 'ECE'), ('CSE', 'CSE'), ('MECH', 'MECH')], max_length=100),
        ),
    ]
