# Generated by Django 5.0.6 on 2024-06-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_alter_staffdetails_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='department',
            field=models.CharField(choices=[('NAN', 'NAN'), ('ECE', 'ECE'), ('CSE', 'CSE'), ('MECH', 'MECH')], max_length=100),
        ),
    ]
