# Generated by Django 5.0.6 on 2024-06-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_alter_staffdetails_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('casual_remaining', models.CharField(max_length=50)),
            ],
        ),
    ]
