# Generated by Django 5.0.6 on 2024-06-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_leave_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_availability',
            name='lop_remaining',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='leave_availability',
            name='casual_remaining',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
