# Generated by Django 5.0.6 on 2024-06-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_leave_availability_lop_remaining_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave_availability',
            old_name='lop_remaining',
            new_name='medical_leave_remaining',
        ),
        migrations.AddField(
            model_name='leave_availability',
            name='onduty_remaining',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='leave_availability',
            name='vaccation_remaining',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
