# Generated by Django 5.0.6 on 2024-06-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0017_rename_lop_remaining_leave_availability_medical_leave_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_availability',
            name='ch_leave_remaining',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='leave_availability',
            name='earn_leave_remaining',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
