# Generated by Django 5.0.6 on 2024-06-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0018_leave_availability_ch_leave_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='otp',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
