# Generated by Django 5.0.6 on 2024-06-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0020_alter_staffdetails_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='notification_display',
            field=models.BooleanField(default=False),
        ),
    ]
