# Generated by Django 5.0.6 on 2024-06-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0021_staffdetails_notification_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='notification_message',
            field=models.CharField(default='', max_length=100),
        ),
    ]
