# Generated by Django 5.0.6 on 2024-07-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0022_staffdetails_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_availability',
            name='initial_casual_remaining',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='leave_availability',
            name='initial_ch_leave_remaining',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='leave_availability',
            name='initial_earn_leave_remaining',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='leave_availability',
            name='initial_medical_leave_remaining',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='leave_availability',
            name='initial_onduty_remaining',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='leave_availability',
            name='initial_vaccation_remaining',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='lop_leave',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='department',
            field=models.CharField(choices=[('ECE', 'ECE'), ('CSE', 'CSE'), ('EIE', 'EIE'), ('MATHS', 'MATHS'), ('CHEMISTRY', 'CHEMISTRY'), ('ENGLISH', 'ENGLISH'), ('PHYSICS', 'PHYSICS'), ('RAE', 'RAE'), ('MECH', 'MECH'), ('EEE', 'EEE'), ('BME', 'BME'), ('AERO', 'AERO'), ('CIVIL', 'CIVIL'), ('IT', 'IT'), ('NANO', 'NANO'), ('AIDS', 'AIDS'), ('MBA', 'MBA'), ('NT', 'NT')], max_length=100),
        ),
    ]
