# Generated by Django 5.0.6 on 2024-07-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0023_leave_availability_initial_casual_remaining_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='default_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual_leave_default', models.IntegerField(default=12)),
                ('LOP_leave_default', models.IntegerField(default=0)),
                ('CH_leave_default', models.IntegerField(default=0)),
                ('medicalLeave_default', models.IntegerField(default=5)),
                ('earnLeave_default', models.IntegerField(default=5)),
                ('vaccationLeave_default', models.IntegerField(default=15)),
                ('specialOnduty_default', models.IntegerField(default=0)),
                ('onDuty_default', models.IntegerField(default=14)),
            ],
        ),
    ]
