# Generated by Django 5.0.6 on 2024-07-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0026_staffdepartment_alter_staffdetails_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdepartment',
            name='name',
        ),
        migrations.AddField(
            model_name='staffdepartment',
            name='departments',
            field=models.JSONField(default=list),
        ),
    ]
